---
# tasks file for debug

- name: collect package facts
  package_facts:
  when:
    - ansible_os_family not in ["Alpine", "Suse"]

- name: collect service_facts
  service_facts:

- name: show vars
  debug:
    var: vars
