---
# tasks file for debug

- name: collect package facts
  package_facts:
  when:
    - ansible_os_family not in ["Alpine", "Suse"]

- name: collect service_facts
  service_facts:
  when:
    - ansible_distribution != "Debian" and ansible_distribution_release != "bullseye" or
      ansible_distribution != "Fedora" and ansible_distribution_major_version != 32 or
      ansible_distribution != "Ubuntu" and ansible_distribution_release != "focal"

- name: show vars
  debug:
    var: vars
