---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: debug-debian
    box: debian/stretch64
  - name: debug-fedora
    box: fedora/30-cloud-base
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  inventory:
    host_vars:
      debug-fedora:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
scenario:
  name: vagrant
